/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './pages/_app/settings'
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard'
import { Route as AppSessionsIndexRouteImport } from './pages/_app/sessions/index'
import { Route as AuthResetPasswordTokenRouteImport } from './pages/_auth/reset-password.$token'
import { Route as AppEventIdDashboardRouteImport } from './pages/_app/$eventId/dashboard'
import { Route as AppEventIdTicketsIndexRouteImport } from './pages/_app/$eventId/tickets/index'
import { Route as AppEventIdPaymentsIndexRouteImport } from './pages/_app/$eventId/payments/index'
import { Route as AppEventIdMembersIndexRouteImport } from './pages/_app/$eventId/members/index'
import { Route as AppEventIdEventEditRouteImport } from './pages/_app/$eventId/event/edit'
import { Route as AppEventIdMembersImportIndexRouteImport } from './pages/_app/$eventId/members/import/index'
import { Route as AppEventIdMembersExportIndexRouteImport } from './pages/_app/$eventId/members/export/index'
import { Route as AppEventIdMemberIdIndexRouteImport } from './pages/_app/$eventId/member/$id/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppEventIdDashboardRoute = AppEventIdDashboardRouteImport.update({
  id: '/$eventId/dashboard',
  path: '/$eventId/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIdTicketsIndexRoute = AppEventIdTicketsIndexRouteImport.update({
  id: '/$eventId/tickets/',
  path: '/$eventId/tickets/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIdPaymentsIndexRoute = AppEventIdPaymentsIndexRouteImport.update({
  id: '/$eventId/payments/',
  path: '/$eventId/payments/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIdMembersIndexRoute = AppEventIdMembersIndexRouteImport.update({
  id: '/$eventId/members/',
  path: '/$eventId/members/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIdEventEditRoute = AppEventIdEventEditRouteImport.update({
  id: '/$eventId/event/edit',
  path: '/$eventId/event/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIdMembersImportIndexRoute =
  AppEventIdMembersImportIndexRouteImport.update({
    id: '/$eventId/members/import/',
    path: '/$eventId/members/import/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppEventIdMembersExportIndexRoute =
  AppEventIdMembersExportIndexRouteImport.update({
    id: '/$eventId/members/export/',
    path: '/$eventId/members/export/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppEventIdMemberIdIndexRoute = AppEventIdMemberIdIndexRouteImport.update({
  id: '/$eventId/member/$id/',
  path: '/$eventId/member/$id/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$eventId/dashboard': typeof AppEventIdDashboardRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/$eventId/event/edit': typeof AppEventIdEventEditRoute
  '/$eventId/members': typeof AppEventIdMembersIndexRoute
  '/$eventId/payments': typeof AppEventIdPaymentsIndexRoute
  '/$eventId/tickets': typeof AppEventIdTicketsIndexRoute
  '/$eventId/member/$id': typeof AppEventIdMemberIdIndexRoute
  '/$eventId/members/export': typeof AppEventIdMembersExportIndexRoute
  '/$eventId/members/import': typeof AppEventIdMembersImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$eventId/dashboard': typeof AppEventIdDashboardRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/$eventId/event/edit': typeof AppEventIdEventEditRoute
  '/$eventId/members': typeof AppEventIdMembersIndexRoute
  '/$eventId/payments': typeof AppEventIdPaymentsIndexRoute
  '/$eventId/tickets': typeof AppEventIdTicketsIndexRoute
  '/$eventId/member/$id': typeof AppEventIdMemberIdIndexRoute
  '/$eventId/members/export': typeof AppEventIdMembersExportIndexRoute
  '/$eventId/members/import': typeof AppEventIdMembersImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/$eventId/dashboard': typeof AppEventIdDashboardRoute
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/$eventId/event/edit': typeof AppEventIdEventEditRoute
  '/_app/$eventId/members/': typeof AppEventIdMembersIndexRoute
  '/_app/$eventId/payments/': typeof AppEventIdPaymentsIndexRoute
  '/_app/$eventId/tickets/': typeof AppEventIdTicketsIndexRoute
  '/_app/$eventId/member/$id/': typeof AppEventIdMemberIdIndexRoute
  '/_app/$eventId/members/export/': typeof AppEventIdMembersExportIndexRoute
  '/_app/$eventId/members/import/': typeof AppEventIdMembersImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$eventId/dashboard'
    | '/reset-password/$token'
    | '/sessions'
    | '/$eventId/event/edit'
    | '/$eventId/members'
    | '/$eventId/payments'
    | '/$eventId/tickets'
    | '/$eventId/member/$id'
    | '/$eventId/members/export'
    | '/$eventId/members/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$eventId/dashboard'
    | '/reset-password/$token'
    | '/sessions'
    | '/$eventId/event/edit'
    | '/$eventId/members'
    | '/$eventId/payments'
    | '/$eventId/tickets'
    | '/$eventId/member/$id'
    | '/$eventId/members/export'
    | '/$eventId/members/import'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/$eventId/dashboard'
    | '/_auth/reset-password/$token'
    | '/_app/sessions/'
    | '/_app/$eventId/event/edit'
    | '/_app/$eventId/members/'
    | '/_app/$eventId/payments/'
    | '/_app/$eventId/tickets/'
    | '/_app/$eventId/member/$id/'
    | '/_app/$eventId/members/export/'
    | '/_app/$eventId/members/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/$eventId/dashboard': {
      id: '/_app/$eventId/dashboard'
      path: '/$eventId/dashboard'
      fullPath: '/$eventId/dashboard'
      preLoaderRoute: typeof AppEventIdDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/tickets/': {
      id: '/_app/$eventId/tickets/'
      path: '/$eventId/tickets'
      fullPath: '/$eventId/tickets'
      preLoaderRoute: typeof AppEventIdTicketsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/payments/': {
      id: '/_app/$eventId/payments/'
      path: '/$eventId/payments'
      fullPath: '/$eventId/payments'
      preLoaderRoute: typeof AppEventIdPaymentsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/members/': {
      id: '/_app/$eventId/members/'
      path: '/$eventId/members'
      fullPath: '/$eventId/members'
      preLoaderRoute: typeof AppEventIdMembersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/event/edit': {
      id: '/_app/$eventId/event/edit'
      path: '/$eventId/event/edit'
      fullPath: '/$eventId/event/edit'
      preLoaderRoute: typeof AppEventIdEventEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/members/import/': {
      id: '/_app/$eventId/members/import/'
      path: '/$eventId/members/import'
      fullPath: '/$eventId/members/import'
      preLoaderRoute: typeof AppEventIdMembersImportIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/members/export/': {
      id: '/_app/$eventId/members/export/'
      path: '/$eventId/members/export'
      fullPath: '/$eventId/members/export'
      preLoaderRoute: typeof AppEventIdMembersExportIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$eventId/member/$id/': {
      id: '/_app/$eventId/member/$id/'
      path: '/$eventId/member/$id'
      fullPath: '/$eventId/member/$id'
      preLoaderRoute: typeof AppEventIdMemberIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppEventIdDashboardRoute: typeof AppEventIdDashboardRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppEventIdEventEditRoute: typeof AppEventIdEventEditRoute
  AppEventIdMembersIndexRoute: typeof AppEventIdMembersIndexRoute
  AppEventIdPaymentsIndexRoute: typeof AppEventIdPaymentsIndexRoute
  AppEventIdTicketsIndexRoute: typeof AppEventIdTicketsIndexRoute
  AppEventIdMemberIdIndexRoute: typeof AppEventIdMemberIdIndexRoute
  AppEventIdMembersExportIndexRoute: typeof AppEventIdMembersExportIndexRoute
  AppEventIdMembersImportIndexRoute: typeof AppEventIdMembersImportIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppEventIdDashboardRoute: AppEventIdDashboardRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppEventIdEventEditRoute: AppEventIdEventEditRoute,
  AppEventIdMembersIndexRoute: AppEventIdMembersIndexRoute,
  AppEventIdPaymentsIndexRoute: AppEventIdPaymentsIndexRoute,
  AppEventIdTicketsIndexRoute: AppEventIdTicketsIndexRoute,
  AppEventIdMemberIdIndexRoute: AppEventIdMemberIdIndexRoute,
  AppEventIdMembersExportIndexRoute: AppEventIdMembersExportIndexRoute,
  AppEventIdMembersImportIndexRoute: AppEventIdMembersImportIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
