/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PokemonIndexRouteImport } from './pages/pokemon/index'
import { Route as PokemonIdRouteImport } from './pages/pokemon/$id'
import { Route as AuthenticatedSettingsRouteImport } from './pages/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './pages/_authenticated/dashboard'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as hiddenFolderFirstLevelRouteImport } from './pages/(hidden-folder)/first-level'
import { Route as OneTwoThreeRouteImport } from './pages/one.two.three'
import { Route as FooBarBazRouteImport } from './pages/foo/bar/baz'
import { Route as hiddenFolderLayoutsVisibleLayoutRouteImport } from './pages/(hidden-folder)/layouts/visibleLayout'
import { Route as hiddenFolderLayoutsHiddenLayoutRouteImport } from './pages/(hidden-folder)/layouts/_hiddenLayout'
import { Route as hiddenFolderLayoutsVisibleLayoutFooRouteImport } from './pages/(hidden-folder)/layouts/visibleLayout/foo'
import { Route as hiddenFolderLayoutsVisibleLayoutBarRouteImport } from './pages/(hidden-folder)/layouts/visibleLayout/bar'
import { Route as hiddenFolderLayoutsHiddenLayoutFooRouteImport } from './pages/(hidden-folder)/layouts/_hiddenLayout/foo'
import { Route as hiddenFolderLayoutsHiddenLayoutBarRouteImport } from './pages/(hidden-folder)/layouts/_hiddenLayout/bar'

const hiddenFolderLayoutsRouteImport = createFileRoute(
  '/(hidden-folder)/layouts',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const hiddenFolderLayoutsRoute = hiddenFolderLayoutsRouteImport.update({
  id: '/(hidden-folder)/layouts',
  path: '/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIdRoute = PokemonIdRouteImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const hiddenFolderFirstLevelRoute = hiddenFolderFirstLevelRouteImport.update({
  id: '/(hidden-folder)/first-level',
  path: '/first-level',
  getParentRoute: () => rootRouteImport,
} as any)
const OneTwoThreeRoute = OneTwoThreeRouteImport.update({
  id: '/one/two/three',
  path: '/one/two/three',
  getParentRoute: () => rootRouteImport,
} as any)
const FooBarBazRoute = FooBarBazRouteImport.update({
  id: '/foo/bar/baz',
  path: '/foo/bar/baz',
  getParentRoute: () => rootRouteImport,
} as any)
const hiddenFolderLayoutsVisibleLayoutRoute =
  hiddenFolderLayoutsVisibleLayoutRouteImport.update({
    id: '/visibleLayout',
    path: '/visibleLayout',
    getParentRoute: () => hiddenFolderLayoutsRoute,
  } as any)
const hiddenFolderLayoutsHiddenLayoutRoute =
  hiddenFolderLayoutsHiddenLayoutRouteImport.update({
    id: '/_hiddenLayout',
    getParentRoute: () => hiddenFolderLayoutsRoute,
  } as any)
const hiddenFolderLayoutsVisibleLayoutFooRoute =
  hiddenFolderLayoutsVisibleLayoutFooRouteImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)
const hiddenFolderLayoutsVisibleLayoutBarRoute =
  hiddenFolderLayoutsVisibleLayoutBarRouteImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsVisibleLayoutRoute,
  } as any)
const hiddenFolderLayoutsHiddenLayoutFooRoute =
  hiddenFolderLayoutsHiddenLayoutFooRouteImport.update({
    id: '/foo',
    path: '/foo',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)
const hiddenFolderLayoutsHiddenLayoutBarRoute =
  hiddenFolderLayoutsHiddenLayoutBarRouteImport.update({
    id: '/bar',
    path: '/bar',
    getParentRoute: () => hiddenFolderLayoutsHiddenLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/pokemon': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first-level': typeof hiddenFolderFirstLevelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/pokemon': typeof PokemonIndexRoute
  '/layouts': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/layouts/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/layouts/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(hidden-folder)/first-level': typeof hiddenFolderFirstLevelRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/(hidden-folder)/layouts': typeof hiddenFolderLayoutsRouteWithChildren
  '/(hidden-folder)/layouts/_hiddenLayout': typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  '/(hidden-folder)/layouts/visibleLayout': typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
  '/foo/bar/baz': typeof FooBarBazRoute
  '/one/two/three': typeof OneTwoThreeRoute
  '/(hidden-folder)/layouts/_hiddenLayout/bar': typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  '/(hidden-folder)/layouts/_hiddenLayout/foo': typeof hiddenFolderLayoutsHiddenLayoutFooRoute
  '/(hidden-folder)/layouts/visibleLayout/bar': typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  '/(hidden-folder)/layouts/visibleLayout/foo': typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/first-level'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/pokemon/$id'
    | '/pokemon'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/first-level'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/pokemon/$id'
    | '/pokemon'
    | '/layouts'
    | '/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/layouts/bar'
    | '/layouts/foo'
    | '/layouts/visibleLayout/bar'
    | '/layouts/visibleLayout/foo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(hidden-folder)/first-level'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/pokemon/$id'
    | '/pokemon/'
    | '/(hidden-folder)/layouts'
    | '/(hidden-folder)/layouts/_hiddenLayout'
    | '/(hidden-folder)/layouts/visibleLayout'
    | '/foo/bar/baz'
    | '/one/two/three'
    | '/(hidden-folder)/layouts/_hiddenLayout/bar'
    | '/(hidden-folder)/layouts/_hiddenLayout/foo'
    | '/(hidden-folder)/layouts/visibleLayout/bar'
    | '/(hidden-folder)/layouts/visibleLayout/foo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  hiddenFolderFirstLevelRoute: typeof hiddenFolderFirstLevelRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  PokemonIdRoute: typeof PokemonIdRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  hiddenFolderLayoutsRoute: typeof hiddenFolderLayoutsRouteWithChildren
  FooBarBazRoute: typeof FooBarBazRoute
  OneTwoThreeRoute: typeof OneTwoThreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hidden-folder)/layouts': {
      id: '/(hidden-folder)/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof hiddenFolderLayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hidden-folder)/first-level': {
      id: '/(hidden-folder)/first-level'
      path: '/first-level'
      fullPath: '/first-level'
      preLoaderRoute: typeof hiddenFolderFirstLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/two/three': {
      id: '/one/two/three'
      path: '/one/two/three'
      fullPath: '/one/two/three'
      preLoaderRoute: typeof OneTwoThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foo/bar/baz': {
      id: '/foo/bar/baz'
      path: '/foo/bar/baz'
      fullPath: '/foo/bar/baz'
      preLoaderRoute: typeof FooBarBazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(hidden-folder)/layouts/visibleLayout': {
      id: '/(hidden-folder)/layouts/visibleLayout'
      path: '/visibleLayout'
      fullPath: '/layouts/visibleLayout'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutRouteImport
      parentRoute: typeof hiddenFolderLayoutsRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout': {
      id: '/(hidden-folder)/layouts/_hiddenLayout'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutRouteImport
      parentRoute: typeof hiddenFolderLayoutsRoute
    }
    '/(hidden-folder)/layouts/visibleLayout/foo': {
      id: '/(hidden-folder)/layouts/visibleLayout/foo'
      path: '/foo'
      fullPath: '/layouts/visibleLayout/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutFooRouteImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutRoute
    }
    '/(hidden-folder)/layouts/visibleLayout/bar': {
      id: '/(hidden-folder)/layouts/visibleLayout/bar'
      path: '/bar'
      fullPath: '/layouts/visibleLayout/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsVisibleLayoutBarRouteImport
      parentRoute: typeof hiddenFolderLayoutsVisibleLayoutRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout/foo': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/foo'
      path: '/foo'
      fullPath: '/layouts/foo'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutFooRouteImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutRoute
    }
    '/(hidden-folder)/layouts/_hiddenLayout/bar': {
      id: '/(hidden-folder)/layouts/_hiddenLayout/bar'
      path: '/bar'
      fullPath: '/layouts/bar'
      preLoaderRoute: typeof hiddenFolderLayoutsHiddenLayoutBarRouteImport
      parentRoute: typeof hiddenFolderLayoutsHiddenLayoutRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface hiddenFolderLayoutsHiddenLayoutRouteChildren {
  hiddenFolderLayoutsHiddenLayoutBarRoute: typeof hiddenFolderLayoutsHiddenLayoutBarRoute
  hiddenFolderLayoutsHiddenLayoutFooRoute: typeof hiddenFolderLayoutsHiddenLayoutFooRoute
}

const hiddenFolderLayoutsHiddenLayoutRouteChildren: hiddenFolderLayoutsHiddenLayoutRouteChildren =
  {
    hiddenFolderLayoutsHiddenLayoutBarRoute:
      hiddenFolderLayoutsHiddenLayoutBarRoute,
    hiddenFolderLayoutsHiddenLayoutFooRoute:
      hiddenFolderLayoutsHiddenLayoutFooRoute,
  }

const hiddenFolderLayoutsHiddenLayoutRouteWithChildren =
  hiddenFolderLayoutsHiddenLayoutRoute._addFileChildren(
    hiddenFolderLayoutsHiddenLayoutRouteChildren,
  )

interface hiddenFolderLayoutsVisibleLayoutRouteChildren {
  hiddenFolderLayoutsVisibleLayoutBarRoute: typeof hiddenFolderLayoutsVisibleLayoutBarRoute
  hiddenFolderLayoutsVisibleLayoutFooRoute: typeof hiddenFolderLayoutsVisibleLayoutFooRoute
}

const hiddenFolderLayoutsVisibleLayoutRouteChildren: hiddenFolderLayoutsVisibleLayoutRouteChildren =
  {
    hiddenFolderLayoutsVisibleLayoutBarRoute:
      hiddenFolderLayoutsVisibleLayoutBarRoute,
    hiddenFolderLayoutsVisibleLayoutFooRoute:
      hiddenFolderLayoutsVisibleLayoutFooRoute,
  }

const hiddenFolderLayoutsVisibleLayoutRouteWithChildren =
  hiddenFolderLayoutsVisibleLayoutRoute._addFileChildren(
    hiddenFolderLayoutsVisibleLayoutRouteChildren,
  )

interface hiddenFolderLayoutsRouteChildren {
  hiddenFolderLayoutsHiddenLayoutRoute: typeof hiddenFolderLayoutsHiddenLayoutRouteWithChildren
  hiddenFolderLayoutsVisibleLayoutRoute: typeof hiddenFolderLayoutsVisibleLayoutRouteWithChildren
}

const hiddenFolderLayoutsRouteChildren: hiddenFolderLayoutsRouteChildren = {
  hiddenFolderLayoutsHiddenLayoutRoute:
    hiddenFolderLayoutsHiddenLayoutRouteWithChildren,
  hiddenFolderLayoutsVisibleLayoutRoute:
    hiddenFolderLayoutsVisibleLayoutRouteWithChildren,
}

const hiddenFolderLayoutsRouteWithChildren =
  hiddenFolderLayoutsRoute._addFileChildren(hiddenFolderLayoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  hiddenFolderFirstLevelRoute: hiddenFolderFirstLevelRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  PokemonIdRoute: PokemonIdRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  hiddenFolderLayoutsRoute: hiddenFolderLayoutsRouteWithChildren,
  FooBarBazRoute: FooBarBazRoute,
  OneTwoThreeRoute: OneTwoThreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
